name: "Destroy Terraform"

on:
  workflow_dispatch: 

permissions:
  contents: read

jobs:
  destroy:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.11.2


    - name: Terraform Init
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID : ${{secrets.AWS_SECRET_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    - name: Select Terraform Workspace
      run: terraform workspace new dev
        
    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Destroy
      run: terraform destroy -var-file="inputs.tfvars" -auto-approve
      env:
        AWS_ACCESS_KEY_ID : ${{secrets.AWS_SECRET_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        